version: "2"

services:
    zookeeper001:
        restart: always
        image: jplock/zookeeper:3.4.6
        ports:
            - "32776:2181"
        expose:
            - 2181
            - 2287
            - 3387
        volumes:
            - $PWD/zookeeper001/data:/tmp/data
            - $PWD/zookeeper001/log:/tmp/log
            - $PWD/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
    
    zookeeper002:
        restart: always
        image: jplock/zookeeper:3.4.6
        ports:
            - "32777:2181"
        expose:
            - 2181
            - 2287
            - 3387
        volumes:
            - $PWD/zookeeper002/data:/tmp/data
            - $PWD/zookeeper002/log:/tmp/log
            - $PWD/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
    
    zookeeper003:
        restart: always
        image: jplock/zookeeper:3.4.6
        ports:
            - "32778:2181"
        expose:
            - 2181
            - 2287
            - 3387
        volumes:
            - $PWD/zookeeper003/data:/tmp/data
            - $PWD/zookeeper003/log:/tmp/log
            - $PWD/zoo.cfg:/opt/zookeeper/conf/zoo.cfg
    
