version: '2'

services:
    skydns:
        image: skydns:ubuntu14.04
        links:
            - etcd
        ports:
            - "53:53"
            - "53:53/udp"


    etcd:
        image: quay.io/coreos/etcd:v2.3.1

